### ISSUE TITLE
Gitignore

### ISSUE THREAD

**Issue by OlivierGeorgeon** [UCLy/LittleAI#20]
Problème: on ne peut plus chekcout la branche main après avoir installé package.json en étant dans la branche stageVal. 
Suspicion: problème avec le .gitignore n'est pas versonné dans la branche stageVal.

**Comment by Valentinfavre** [comment]
Correctif appliqué !

**Comment by OlivierGeorgeon** [comment]
Parfait ! ca résoud le problème.
