### ISSUE TITLE
Calcer la méthode de Mr.Georgeon pour gérer les traces

### ISSUE THREAD

**Issue by FTholin** [UCLy/LittleAI#8]

**Comment by Valentinfavre** [comment]
Level 4 example : 
Deux cube bloque le robot et Il faut le faire avancé et faire demi tour ( Si le cube effectue un movement sans avoir d'obstacle le compteur de score prends un.
Exemple ( M-R-M --> M--RM (+1)) (M = Mur, R= Robot)
